### PR TITLE
Update dependencies for Java 11 support

### PR DESCRIPTION
**Pull request by ijuma**
cglib, bytebuddy, javassist and easymock.

### CODE REVIEW

**Comment by ijuma** [comment]
cc @thekingnothing

**Comment by ijuma** [comment]
Looks like some code no longer compiles with the new version of EasyMock. Will look into that later.

**Comment by ijuma** [comment]
Hmm, compiling with the new `EasyMock` version seems to cause problems:

```
samples.powermockito.junit4.agent.AnnotationUsageTest > annotationsAreEnabledWhenUsingTheJUnitRule[0] FAILED
    java.lang.VerifyError: Expecting a stackmap frame at branch target 38
    Exception Details:
      Location:
        org/easymock/EasyMockSupport.resetAll()V @16: ifeq
      Reason:
        Expected stackmap frame at this location.
      Bytecode:
        0x0000000: 2ab4 0016 b900 7201 004c 2bb9 0078 0100
        0x0000010: 9900 162b b900 7c01 00c0 0021 4d2c b900
        0x0000020: 8401 00a7 ffe7 b1           
```

cc @henri-tremblay in case he has any thoughts.

As an aside, 2.0.0-RC.2 does not include all the modules. For example: https://repo1.maven.org/maven2/org/powermock/powermock-module-junit4/

**Comment by thekingn0thing** [comment]
@ijuma the 2.0.0-RC.2 should not be sync to  Maven central at all. I didn't add [ci maven-central-release] to comments. I wanted to wait for your pull request before releasing artefacts to the central repository.

**Comment by ijuma** [comment]
That makes sense with regards to 2.0.0-RC.2, thanks (I misread the build output).

**Comment by henri-tremblay** [comment]
It looks like a call to `resetAll` done by generated code without a stackmap. Last time I saw that was because I was on an old ASM or Cglib I think. It is really far in my head. A workaround might have been to tell the code it's pre Java 7 (I think that's when stackmap was introduce). All this is from top of my head. The problem comes possible by EasyMock being Java 8 code now so what you were doing with it isn't working anymore. Cross your fingers you won't have to create a stackmap.

**Comment by ijuma** [comment]
@thekingnothing any thoughts on how to fix this? Otherwise, we can maybe stick to EasyMock 3.6 for now.

**Comment by henri-tremblay** [comment]
That would be sad sad sad. I can have a look but in a couple of days.

**Comment by thekingn0thing** [comment]
Usually, such exception happens when bytecode framework fails to track either stack map or local variables (it was main trouble for me when I started migrate to ByteBuddy).

Usually, upgrading to latest version of Javassist helps. However, as I see we are trying to use the latest version of Javassist.

I can create a test to check what bytecode transformation leads to the exception and then raise a defect for Javassist. Meanwhile, we can try to use previous version of Javassist.

Best Regards,
Artur Zagretdinov

On 31 Oct 2018, at 16:21, Henri Tremblay <notifications@github.com<mailto:notifications@github.com>> wrote:


That would be sad sad sad. I can have a look but in a couple of days.

**Comment by ijuma** [comment]
javassist 3.24.0-GA has been released, but using that results in more test failures:

```
AnnotationUsageTest. annotationsAreEnabledWhenUsingTheJUnitRule[0]
AnnotationUsageTest. annotationsAreEnabledWhenUsingTheJUnitRule[1]
LargeMethodTest. largeMethodShouldBeAbleToBeMocked
LargeMethodTest. largeMethodShouldBeAbleToBeMockedAndThrowException
LargeMethodTest. largeMethodShouldBeAbleToBeSuppressed
LargeMethodTest. largeMethodShouldBeOverridden
```

The new failures are not particularly informative:

```
java.lang.NoClassDefFoundError: Could not initialize class org.powermock.api.easymock.EasyMockConfiguration
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1854)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:706)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.junit4.rule.PowerMockStatement.injectMocksUsingAnnotationEnabler(PowerMockRule.java:125)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:71)
```

**Comment by henri-tremblay** [comment]
Which Java version are you using? Because I did a `gradle build` using Java
8 and 9, it worked nicely. However, with Java 11 is doesn't compile because
Activation has been removed.

BTW, is there a build and install notice somewhere? Because, for instance,
importing the project in IntelliJ doesn't create any module. Slightly
annoying.

Le sam. 3 nov. 2018 13 h 21, Ismael Juma <notifications@github.com> a
écrit :

**Comment by thekingn0thing** [comment]
@henri-tremblay, you may use `/gradlew idea` to generate idea files and the open in IDE.

**Comment by thekingn0thing** [comment]
As I see, the tests are falling only in case if PowerMock uses in agent mode. In addition, the tests are falling randomly when different EasyMock methods are called. 

This root cause of the  java.lang.NoClassDefFoundError is that  `org.powermock.api.easymock.EasyMockConfiguration` has static initilization where `EasyMockSupport` class is loaded. 

> java.lang.NoClassDefFoundError: Could not initialize class org.powermock.api.easymock.EasyMockConfiguration

**Comment by ijuma** [comment]
The errors above were with Java 8. I had tried Java 11 first and got the activation issue too. I pushed the javassist upgrade to check what happens in CI.

**Comment by thekingn0thing** [comment]
Interesting moment, that PowerMock should not modify EasyMock classes, but only load them with ucstom class loader. This logic is hardcoded in PowerMockClassLoader.

**Comment by ijuma** [comment]
CI after the javassist upgrade:

```
6 tests completed, 6 failed
Finished generating test XML results (0.016 secs) into: /home/travis/build/powermock/powermock/tests/easymock/junit4-agent/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.006 secs) into: /home/travis/build/powermock/powermock/tests/easymock/junit4-agent/build/reports/tests/test
:tests:easymock:junit4-agent:test (Thread[main,5,main]) completed. Took 5.307 secs.
```

**Comment by thekingn0thing** [comment]
I thinking about ignoring agent's tests and create an issue to investigate what the difference between agent and class loader ways bytecode transformation.

**Comment by ijuma** [comment]
@thekingnothing When is agent mode used?

**Comment by ijuma** [comment]
@thekingnothing I pushed a commit that ignores the agent tests that were failing.

**Comment by thekingn0thing** [comment]
There are 3 ways use PowerMock.

1) Via jUnit runner and classloader - preferable way as PowerMock classloader so all feature available. However limited use with over jUnit runners, does not work with Jacoco online instrumentation.
2) via jUnit rules and class loader. Although PowerMock classloader is still used to load classes, a test class with all its dependencies are reloaded via serialisation to xml. So it’s around two times slower and have the issue that not all classes can be serialised.
3) jUnit rule and agent - not all features available as byte code modification is limited via agent. However, works with all jUnit’s runners and does not required serialisation.

I guess that agents tries to modify EasyMock classes, when class loader - not.

Best Regards,
Artur Zagretdinov

On 4 Nov 2018, at 17:34, Ismael Juma <notifications@github.com<mailto:notifications@github.com>> wrote:


@thekingnothing<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthekingnothing&data=02%7C01%7C%7Cf54685ae74734ff988b308d6427bd4bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636769496943182368&sdata=tI16v8beRwIZ2p1HJoTN1LDVnKQM5FrwJUJJ98eOeWI%3D&reserved=0> I pushed a commit that ignores the agent tests that were failing.

**Comment by ijuma** [comment]
Thanks for the 2.0.0 RC3 release. Kafka has been updated to use it along with EasyMock 4.0.1:

https://github.com/apache/kafka/pull/5846

**Comment by thekingn0thing** [comment]
Thanks for your pull request.

**Pull request merged**
