### PR TITLE
Support Mockito 2.4.0 for PowerMock 1.x

### PR DESCRIPTION
**Pull request by gstamac**
I added support for Mockito 2.4.0. Reporter couldn't be modified because it is static now.

### CODE REVIEW

**Comment by gstamac** [comment]
I see there are a lot of tests failing for Mockito2. I just noticed I ran the tests on my machine incorrectly (I used -Dmockito2 instead of -Pmockito2). Sorry for that. Most of the functionality works there are problems with using the rules. I'll try to fix it.

**Comment by thekingnothing** [comment]
Thank you for trying tackle this issue. Supporting mockito 2 is a most wanted feature. But, I think it will be a temporary solution for Powermock, because it still uses cglib and uses repacked mockito classes. 

Anyway, I'll review your pull request during next week and I'll try to merge it with Gradle branch.

**Comment by gstamac** [comment]
I finally fixed large method tests. The problem was verifyStatic was still "turned on" when next test started. When next test tried to set the mock Mockito tried to verify the method instead of setting the mock. That's why I added mockingProgress().reset to mockStatic.

**Comment by szczepiq** [comment]
Hey guys, nice work on supporting Mockito! Thank you!

I'm the founder of Mockito and took a quick look at the PR. It looks like it uses a lot of internal classes of Mockito (all classes that come from Mockito's "org.mockito.internal.*"). Internal classes can change without notice. Only public API, e.g. classes from packages that do not contain "internal" are kept compatible in given major version of Mockito ([semver](http://semver.org)). Mockito team is happy to work with you to expose the public APIs you need to make the Powermock integration stable, robust and working with future versions of Mockito.

**Comment by thekingnothing** [comment]
Hi, @szczepiq, 

Thank you for having a time for quick review. Yes, I clearly understand that it's just "kludge" and temporary fix for current issue. Except that PowerMock still uses a lot of "org.mockito.internal.*" packages, it uses a lot repackaged code and continue creates proxies with using Cglib.

I did approve the pull request and included it only by one reason — it is give ability for community to use PowerMock 1 and Mockito 2.  I'll continue work on full current support of Mockito in PowerMock 2 where I'm going migrate to ByteBuddy also.

**Comment by gstamac** [comment]
Hi @thekingnothing,
Do you know where are all my commits? I don't see myself as contributor either. I tried to fetch upstream and got a million merge conflicts.

**Comment by thekingnothing** [comment]
While you was working on supporting Mockito 2, I finished migration to Gradle (migration to Gradle was required to make release process easier).

I changed a structure of the project. As result, it was impossible to merge your pull request due to, as you may see, a tons of conflicts.

I resolved all conflicts by myself to delivery supporting  Mockito 2 to community as soon as possible.

Your pull request contains a lot of commits. I squashed them to a one, to make merging easier. What's why you cannot see your comments commits



Best regrads,
Arthur Zagretdinov


On 16 Feb 2017, at 14:22, Gregor Stamac <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @thekingnothing<https://github.com/thekingnothing>,
Do you know where are all my commits? I don't see myself as contributor either. I tried to fetch upstream and got a million merge conflicts.

**Comment by gstamac** [comment]
Damn. Ok, so I have to reset. Thanks.

**Comment by gstamac** [comment]
More I think about this more I'm disappointment. It feels like my work has been stolen. I know that was not your intention but that's how it feels like. I made a very large contribution and I'm not even mentioned in the list of contributors. And you wouldn't even explain it if I wouldn't notice it myself. Very disrespectful.

**Comment by thekingnothing** [comment]
Which list do you mean?

I added information to release notes that pull request provided by you. And to file https://github.com/powermock/powermock/blob/master/changelog.txt

I also mentioned in commits comments.

Later, when release will be dropped, I'll mentioned in news.

Best regrads,
Arthur Zagretdinov


On 21 Feb 2017, at 16:35, Gregor Stamac <notifications@github.com<mailto:notifications@github.com>> wrote:


More I think about this more I'm disappointment. It feels like my work has been stolen. I know that was not your intention but that's how it feels like. I made a very large contribution and I'm not even mentioned in the list of contributors. And you wouldn't even explain it if I wouldn't notice it myself. Very disrespectful.

**Comment by gstamac** [comment]
I'm talking about [https://github.com/powermock/powermock/graphs/contributors](https://github.com/powermock/powermock/graphs/contributors).

**Comment by thekingnothing** [comment]
If it so important for you, I could revert commit. So you will be able to merge all change by your-self and create a new pull request.
My main goal has been and remains provide solution for community and for all users of PowerMock.

**Comment by gstamac** [comment]
No, don't do that. I reset the repo to your version so I don't have any commits anymore. I don't think it's possible to fix it now. 
As I said before I know your intentions were not bad I just mentioned it so it doesn't happen again. If I was a young developer looking for work this kind of thing could help me get a job.

**Pull request merged**
