### PR TITLE
mockito 4.3.1

### PR DESCRIPTION
**Pull request by sullis**
compatibility with Mockito 4.x

### CODE REVIEW

**Comment by sullis** [comment]
Ready for review @johanhaleby @thekingn0thing

**Comment by sullis** [comment]
cc: @afds

**Review by afds — APPROVED** [review]

**Comment by sullis** [comment]
Can you merge this?  @thekingn0thing

**Comment by sullis** [comment]
Ready to merge. @thekingn0thing

**Comment by nmorkar** [comment]
Ready to merge and release new version, this will fix issue - https://github.com/powermock/powermock/issues/1125

**Comment by valfirst** [comment]
@johanhaleby do you plan to release a new version of PowerMock?

**Comment by thekingn0thing** [comment]
@valfirst and @johanhaleby as for now we don't have infrustucture to do a release. We need to move to github actions or to some other build servers + set up again deploy to maven central.

**Comment by valfirst** [comment]
@thekingn0thing please check my PR https://github.com/powermock/powermock/pull/1122/. I've tested it in my fork: https://github.com/valfirst/powermock/commits/release/3.x

**Comment by jai-bo** [comment]
> @valfirst and @johanhaleby as for now we don't have infrustucture to do a release. We need to move to github actions or to some other build servers + set up again deploy to maven central.

Any plans on the new version release, no latest release for more than 1 year now. Maybe a patch release? 
Issue affecting newer versions.

**Comment by chingjustwe** [comment]
Really looking forward to a new release...

**Comment by gezn** [comment]
When is the new release planned? it is more than a year already from this PR

**Pull request merged**
