### PR TITLE
Make powermock compatible with JUnit 4.12

### PR DESCRIPTION
**Pull request by henri-tremblay**
Here is a basic fix to make powermock work with JUnit 4.12

### CODE REVIEW

**Comment by kcooney** [comment]
Hey, guys. I am one of the maintainers for JUnit. I was hunting around for things that might have broken by JUnit 4.13 and stumbled upon this pull.

Using reflection to access private fields of an internal class sounds fragile. If you have ideas for how we can create a supported API for whatever you are trying to do here, please file a feature request. Note that it's likely that `MethodValidator` (and `JUnit4ClassRunner`) will go away in JUnit 5.0, and there might not be a JUnit 4.13.

**Comment by johanhaleby** [comment]
Hi, 

Yes it's extremely fragile. I would go as far to say that most of the PowerMock  code base is very fragile and it's a nightmare to maintain unfortunately. To be honest it was such a long time ago since I created the Runner so I don't remember all the decisions of why things were done. But one of the things that makes the PowerMockRunner so complex is because something we refer to as "test chunking". What happens is that (potentially) each test method in a class can be executed by its own classloader and the result is merged together in the end. The way this works (if I remember things correctly) is that each of these test methods are actually executed as it's own "test class". To the user it looks like they are running the test class as normal but under the hood several test classes are executed and they report back to the original test class once they have completed to assemble the result. However this feature not only makes the code complex and brittle but it's also not used very often. I think the runner should be rewritten entirely and we should scrap the support for "test chunking". Probably should have been done a long time ago. I just need to find some time to do it :)

**Comment by kcooney** [comment]
Note that the replacement for JUnit4ClassRunner is BlockJUnit4ClassRunner

**Comment by johanhaleby** [comment]
Thanks for letting us know

**Pull request merged**
