### PR TITLE
Shipkit pom customizations

### PR DESCRIPTION
**Pull request by wwilk**
I will make further pom customizations, to keep the same format as it was before introducing shipkit. 
I'm travelling right now so these will be probably small changes, you can wait with merging this PR before all is done. 

Starting with <developers>. Before you had sth like that:
```
    <developer>
      <id>johanhaleby</id>
      <name>Johan Haleby</name>
      <email>johan.haleby at jayway.com</email>
    </developer>
```

Shipkit currently supports format: 
```
    <developer>
      <id>johanhaleby</id>
      <name>Johan Haleby</name>
      <roles>
        <role>Core developer</role>
      </roles>
      <url>https://github.com/johanhaleby</url>
    </developer>
```

@thekingnothing What do you think about it? Is it acceptable or you would like to keep this email for developers? We may think of supporting it in shipkit or customize it here. As you can see I removed code that modified <developers> from powermock code. 

Additionally shipkit generates <contributors> section, that looks like that:
```
    <contributor>
      <name>René Scheibe</name>
      <url>https://github.com/darxriggs</url>
    </contributor>
```

I hope you are ok with that.

### CODE REVIEW

**Comment by wwilk** [comment]
Scm section currently: 
```
  <scm>
    <url>http://github.com/mockito/mockito</url>
    <connection>scm:git:git://github.com/powermock/powermock</connection>
    <developerConnection>scm:git:git://github.com/powermock/powermock</developerConnection>
  </scm>
```

With shipkit: 
```
  <scm>
    <url>https://github.com/powermock/powermock.git</url>
  </scm>
```

Do we need these additional properties?

**Comment by wwilk** [comment]
BTW why is <url> http://github.com/mockito/mockito ?

**Comment by wwilk** [comment]
There is a really subtle difference about <issues> (<system> is "GitHub issues" instead of "GitHub") so I'm removing this section from "publish-maven.gradle".

**Comment by mockitoguy** [comment]
Hey guys. If needed I think we can keep the existing withXml() section in powermock's build.gradle file. withXml() can be used to register multiple actions, each action will manipulate the xml. If shipikit .gradle does not have developers, it does not add this section to the xml at all. So the withXml() from powermockito can simply fill it out.

**Comment by wwilk** [comment]
Yes, of course we can do it, I only wanted to show @thekingnothing what the difference would be if he used it the shipkit way.

**Comment by thekingn0thing** [comment]
@szczepiq thank you for your comments.

@wwilk, I prefer keeping emails in pom.xml instead Github links, because  Github only one of possible services. PowerMock had migration experience from GoogleCode to GitHub. Email it is a general coordinate and a developer could be reached out in easy way.

**Comment by thekingn0thing** [comment]
> By the way why is http://github.com/mockito/mockito 
A good catch.  It's an artifact of the copy-past development style :)

**Comment by thekingn0thing** [comment]
I'm oaky with 
```
  <scm>
    <url>https://github.com/powermock/powermock.git</url>
  </scm>
```

**Comment by thekingn0thing** [comment]
@wwilk could you check last changes. After them build have started fail with compile error: 

```
:powermock-core:compileTestJava/home/travis/build/powermock/powermock/powermock-core/src/test/java/org/powermock/configuration/ConfigurationFactoryImplTest.java:24: error: package org.powermock.api.mockito does not exist
import org.powermock.api.mockito.ConfigurationTestUtils;
```

**Pull request merged**
